[workspace]
members = [
  "zypp-gui",
  "mod_repo",
]

default-members = [
  "zypp-gui",
  "mod_repo",
]

resolver = "2"

[workspace.package]
name = "zypp_gui"
version = "0.3.0"
authors = ["Xiaoguang Wang <sun.wxg@gmail.com>"]
edition = "2018"
