pub static NAME_CONVERT:&'static [(&'static str, &'static str)] = &[
("The Clarkson Open Source Institute (COSI)",
"The.Clarkson.Open.Source.Institute"),
("SUSE Linux Products GmbH",
"SUSE.Linux.Products.GmbH"),
("NAV Communications",
"NAV.Communications"),
("IPHH - Internet Port Hamburg GmbH",
"IPHH-Internet.Port.Hamburg.GmbH"),
("Lysator ACS",
"Lysator.ACS"),
("RPM PBone Search",
"RPM.PBone.Search"),
("Telkom / FOSS-ID - Free Open Source Software Untuk Semua",
"Telkom.FOSS-ID"),
("RWTH Aachen University",
"RWTH.Aachen.University"),
("Princeton University Mathematics",
"Princeton.University.Mathematics"),
("TENET - Tertiary Education Network",
"TENET-Tertiary.Education.Network"),
("AARNet - Australia's Research and Education Network",
"AARNet-Australia"),
("Vectra",
"Vectra"),
("IPACCT Ltd.",
"IPACCT.Ltd"),
("LeadHosts",
"LeadHosts"),
("UNINETT - Norwegian Research Network",
"UNINETT-Norwegian.Research.Network"),
("NLUUG / Surfnet",
"NLUUG.Surfnet"),
("University of Science and Technology of China",
"University.of.Science.and.Technology.of.China"),
("Sultan Qaboos University",
"Sultan.Qaboos.University"),
("23Media GmbH",
"23Media.GmbH"),
("Novell Hungary",
"Novell.Hungary"),
("Linux Kernel Archives (JP)",
"Linux.Kernel.Archives.JP"),
("LiteServer",
"LiteServer"),
("NetiX",
"NetiX"),
("University of Maryland, College Park",
"University.of.Maryland.College.Park"),
("Яндекс - Yandex",
"Яндекс.Yandex"),
("JAIST - Japan Advanced Institute Of Science And Technology",
"JAIST"),
("KLID - Commercial Linux Stakeholders In Denmark",
"KLID-Denmark"),
("WPI ACM",
"WPI.ACM"),
("RpmFind, Lyon",
"RpmFind.Lyon"),
("Host.AG",
"Host.AG"),
("Komunitas openSUSE Indonesia",
"Komunitas.openSUSE.Indonesia"),
("Universidad de Costa Rica",
"Universidad.de.Costa.Rica"),
("Federal University of Paraná, Center for Scientific Computing and Free Software (C3SL)",
"Federal.University"),
("Esslingen University of Applied Sciences",
"Esslingen.University.of.Applied.Sciences"),
("Technische Universität Ilmenau",
"Technische.Universität.Ilmenau"),
("ITCenter of Isfahan University of Technology",
"ITCenter.of.Isfahan.University"),
("National University of Singapore",
"National.University.of.Singapore"),
("openSUSE Heroes - sponsored by QSC AG",
"openSUSE.Heroes-sponsored.by.QSC.AG"),
("CHG - Scientific Center in Chernogolovka RAS",
"CHG-Scientific.Center.in.Chernogolovka.RAS"),
("The Free Mirror Project",
"Free.Mirror"),
("Georgia Institute of Technology",
"Georgia.Institute.of.Technology"),
("Linux Foundation - Portland, Oregon, USA",
"Linux.Foundation.Portland.Oregon.USA"),
("TDS Telecom",
"TDS.Telecom"),
("Virginia Tech Transportation Institute",
"Virginia.Tech.Transportation.Institute"),
("Intergrid",
"Intergrid"),
("iiNet",
"iiNet"),
("FSN . HU",
"FSN.HU"),
("Kelompok Linux Arek Suroboyo",
"Kelompok.Linux.Arek.Suroboyo"),
("Facultad de Derecho, Universidad de la República, Uruguay",
"Facultad.de.Derecho"),
("KINDL&PARTNERI advokatni kancelar s.r.o.",
"KINDL&PARTNERI.advokatni.kancelar.s.r.o."),
("Linux Kernel Archives (US West)",
"Linux.Kernel.Archives.US.West"),
("Netspace Online Systems",
"Netspace.Online.Systems"),
("Beijing Jiaotong University",
"Beijing.Jiaotong.University"),
("Academic Computer Club",
"Academic.Computer.Club"),
("Xgroup.si",
"Xgroup.si"),
("Easy Lee",
"Easy.Lee"),
("Telkom University",
"Telkom.University"),
("Linux Kernel Archives (US East)",
"Linux.Kernel.Archives.US.East"),
("University Of Kent - UK Mirror Service",
"University.Of.Kent-UK.Mirror.Service"),
("GWDG - Gesellschaft für wissenschaftliche Datenverarbeitung mbH Göttingen",
"GWDG"),
("Leaseweb",
"Leaseweb"),
("iHost",
"iHost"),
("CZLUG - Czech Linux Users' Group",
"CZLUG-Czech.Linux.User.Group"),
("ia64-linux.org",
"ia64-linux.org"),
("MGTS, RUE Beltelecom. ByFly ISP",
"MGTS.RUE.Beltelecom.ByFly.ISP"),
("VDS Sunucu",
"VDS.Sunucu"),
("Academic Computer Club Umeå University",
"Academic.Computer.Club.Umeå.University"),
("Datto Inc.",
"Datto.Inc."),
("Datacenter Uzinfocom",
"Datacenter.Uzinfocom"),
("Beijing Foreign Studies University",
"Beijing.Foreign.Studies.University"),
("Repo UGM",
"Repo.UGM"),
("Hostsuisse (ENIDAN Technologies GmbH)",
"Hostsuisse.ENIDAN.Technologies.GmbH"),
("dogado GmbH",
"dogado.GmbH"),
("University of Waterloo Computer Science Club",
"University.of.Waterloo"),
("University of Utah",
"University.of.Utah"),
("Israel Internet Association (ISOC-IL)",
"Israel.Internet.Association"),
("Linder Hard- und Software",
"Linder.Hard-und.Software"),
("NCHC - National Center for High-Performance Computing",
"NCHC"),
("CZ.NIC",
"CZ.NIC"),
("Internode",
"Internode"),
("TheoM’s Mirror Service",
"TheoM’s.Mirror.Service"),
("NetEase",
"NetEase"),
("Tsinghua University TUNA",
"Tsinghua.University"),
("TWAREN - Taiwan Advance Research & Education Network",
"TWAREN"),
("Coreix Ltd",
"Coreix.Ltd"),
("Tomsk State Pedagogical University",
"Tomsk.State.Pedagogical.University"),
("RNL - Técnico Lisboa",
"RNL-Técnico.Lisboa"),
("ETTE.biz",
"ETTE.biz"),
("ibiblio.org - the public's library and digital archive",
"ibiblio.org"),
("University of Crete",
"University.of.Crete"),
("Dalhousie University, Halifax NS",
"Dalhousie.University"),
("Adfinis AG",
"Adfinis.AG"),
("Julius Maximilian University of Würzburg",
"Julius.Maximilian.University.of.Würzburg"),
("nxtHost.com",
"nxtHost.com"),
("University of Bayreuth",
"University.of.Bayreuth"),
("Purdue Linux Users Group",
"Purdue.Linux.Users.Group"),
("Linux Kernel Archives (EU)",
"Linux.Kernel.Archives.EU"),
("Consorcio Ecuatoriano para el Desarrollo de Internet Avanzado",
"Consorcio.Ecuatoriano.para"),
("KDDI R&D Labs",
"KDDI.R&D.Labs"),
("RIKEN's Institute & Centers",
"RIKEN's.Institute&Centers"),
("Easyname GmbH",
"Easyname.GmbH"),
("University of Erlangen-Nürnberg",
"University.of.Erlangen-Nürnberg"),
("Schlund Technologies GmbH",
"Schlund.Technologies.GmbH"),
("University of Kaiserslautern",
"University.of.Kaiserslautern"),
("Alwyzon",
"Alwyzon"),
("FedoraMD project",
"FedoraMD.project"),
("BELNET - The network of knowledge",
"BELNET-The.network.of.knowledge"),
("University of Cyprus, Library",
"University.of.Cyprus.Library"),
("Technische Universität Chemnitz",
"Technische.Universität.Chemnitz"),
("openSUSE Heroes",
"openSUSE.Heroes"),
("Get Hosted Online",
"Get.Hosted.Online"),
("Poznań Supercomputing and Networking Center",
"Poznań.Supercomputing.and.Networking.Center"),
("http://sfo-korg-mirror.kernel.org/",
"sfo-korg-mirror"),
("Siena College",
"Siena.College"),
("KAIST - Korea Advanced Institute of Science and Technology",
"KAIST"),
("Ucom LLC",
"Ucom.LLC"),
("IP Serverone Solutions Sdn Bhd",
"IP.Serverone.Solutions.Sdn.Bhd"),
("Linux Kullanicilari Dernegi, ULAKBIM",
"Linux.Kullanicilari.Dernegi.ULAKBIM"),
("Rochester Institute of Technology - Research Computing",
"Rochester.Institute.of.Technology"),
("Indiana University, Research Technologies Core Services",
"Indiana.University"),
("Lanzhou University Open Source Society",
"Lanzhou.University"),
("Silicon Hill, Student’s Union CTU",
"Silicon.Hill.Student’s.Union.CTU"),
("Rainside",
"Rainside"),
("University of Paderborn",
"University.of.Paderborn"),
("Rotterdam University",
"Rotterdam.University"),
("ICM - Interdisciplinary Center for Mathematical and Computational Modeling",
"ICM"),
("Yuan Ze University",
"Yuan.Ze.University"),
("Rackspace Hosting, Inc.",
"Rackspace.Hosting.Inc."),
("Bernhard M. Wiedemann",
"Bernhard.M.Wiedemann"),
("Harbin Institute of Technology Linux User Group",
"Harbin.Institute.of.Technology"),
("eScience Center, Nanjing University",
"eScience.Center,.Nanjing.University"),
("DEAC",
"DEAC"),
("lagis Internet Serviceprovider",
"lagis.Internet.Serviceprovider"),
("Liquid Telecom",
"Liquid.Telecom"),
("UPC Česká republika",
"UPC.Česká.republika"),
("GARR - The Italian Academic & Research Network",
"GARR-The.Italian.Academic&Research.Network"),
("UNICAMP - University of Campinas",
"UNICAMP"),
("Quantum Mirror",
"Quantum.Mirror"),
("University of Oxford",
"University.of.Oxford"),
("University of Leipzig",
"University.of.Leipzig"),
("openSUSE",
"openSUSE"),
("Binario Cloud / openSUSE Brasil",
"Binario.Cloud"),
("EUserv Internet",
"EUserv.Internet"),
("UFONE",
"UFONE"),
("Shanghai Jiao Tong University Network Information Center",
"Shanghai.Jiao.Tong.University"),
("Funet - Finnish University and Research Network",
"Funet-Finnish.University.and.Research.Network"),
("Elion",
"Elion"),
("Carsten Braun Software Solutions",
"Carsten.Braun.Software.Solutions"),
("Dotsrc.org",
"Dotsrc.org"),
("Free",
"Free"),
("MUUG - Manitoba UNIX User Group",
"MUUG"),
("Esto Internet",
"Esto.Internet"),
("Ivan Barabash",
"Ivan.Barabash"),
("Silicon Valley Web Hosting LLC",
"Silicon.Valley.Web.Hosting.LLC"),
("standaloneInstaller.com",
"standaloneInstaller.com"),
];
