// Generated by gir (https://github.com/gtk-rs/gir @ f3d92ad)
// from /home/home/person/git_hub/gir-files (@ 7d95377)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "PkAuthorizeEnum", sizeof(PkAuthorizeEnum), alignof(PkAuthorizeEnum));
    printf("%s;%zu;%zu\n", "PkBitfield", sizeof(PkBitfield), alignof(PkBitfield));
    printf("%s;%zu;%zu\n", "PkCategory", sizeof(PkCategory), alignof(PkCategory));
    printf("%s;%zu;%zu\n", "PkCategoryClass", sizeof(PkCategoryClass), alignof(PkCategoryClass));
    printf("%s;%zu;%zu\n", "PkClient", sizeof(PkClient), alignof(PkClient));
    printf("%s;%zu;%zu\n", "PkClientClass", sizeof(PkClientClass), alignof(PkClientClass));
    printf("%s;%zu;%zu\n", "PkClientError", sizeof(PkClientError), alignof(PkClientError));
    printf("%s;%zu;%zu\n", "PkClientHelper", sizeof(PkClientHelper), alignof(PkClientHelper));
    printf("%s;%zu;%zu\n", "PkClientHelperClass", sizeof(PkClientHelperClass), alignof(PkClientHelperClass));
    printf("%s;%zu;%zu\n", "PkControl", sizeof(PkControl), alignof(PkControl));
    printf("%s;%zu;%zu\n", "PkControlClass", sizeof(PkControlClass), alignof(PkControlClass));
    printf("%s;%zu;%zu\n", "PkControlError", sizeof(PkControlError), alignof(PkControlError));
    printf("%s;%zu;%zu\n", "PkDesktop", sizeof(PkDesktop), alignof(PkDesktop));
    printf("%s;%zu;%zu\n", "PkDesktopClass", sizeof(PkDesktopClass), alignof(PkDesktopClass));
    printf("%s;%zu;%zu\n", "PkDetails", sizeof(PkDetails), alignof(PkDetails));
    printf("%s;%zu;%zu\n", "PkDetailsClass", sizeof(PkDetailsClass), alignof(PkDetailsClass));
    printf("%s;%zu;%zu\n", "PkDistroUpgrade", sizeof(PkDistroUpgrade), alignof(PkDistroUpgrade));
    printf("%s;%zu;%zu\n", "PkDistroUpgradeClass", sizeof(PkDistroUpgradeClass), alignof(PkDistroUpgradeClass));
    printf("%s;%zu;%zu\n", "PkDistroUpgradeEnum", sizeof(PkDistroUpgradeEnum), alignof(PkDistroUpgradeEnum));
    printf("%s;%zu;%zu\n", "PkEnumMatch", sizeof(PkEnumMatch), alignof(PkEnumMatch));
    printf("%s;%zu;%zu\n", "PkError", sizeof(PkError), alignof(PkError));
    printf("%s;%zu;%zu\n", "PkErrorClass", sizeof(PkErrorClass), alignof(PkErrorClass));
    printf("%s;%zu;%zu\n", "PkErrorEnum", sizeof(PkErrorEnum), alignof(PkErrorEnum));
    printf("%s;%zu;%zu\n", "PkEulaRequired", sizeof(PkEulaRequired), alignof(PkEulaRequired));
    printf("%s;%zu;%zu\n", "PkEulaRequiredClass", sizeof(PkEulaRequiredClass), alignof(PkEulaRequiredClass));
    printf("%s;%zu;%zu\n", "PkExitEnum", sizeof(PkExitEnum), alignof(PkExitEnum));
    printf("%s;%zu;%zu\n", "PkFiles", sizeof(PkFiles), alignof(PkFiles));
    printf("%s;%zu;%zu\n", "PkFilesClass", sizeof(PkFilesClass), alignof(PkFilesClass));
    printf("%s;%zu;%zu\n", "PkFilterEnum", sizeof(PkFilterEnum), alignof(PkFilterEnum));
    printf("%s;%zu;%zu\n", "PkGroupEnum", sizeof(PkGroupEnum), alignof(PkGroupEnum));
    printf("%s;%zu;%zu\n", "PkInfoEnum", sizeof(PkInfoEnum), alignof(PkInfoEnum));
    printf("%s;%zu;%zu\n", "PkItemProgress", sizeof(PkItemProgress), alignof(PkItemProgress));
    printf("%s;%zu;%zu\n", "PkItemProgressClass", sizeof(PkItemProgressClass), alignof(PkItemProgressClass));
    printf("%s;%zu;%zu\n", "PkMediaChangeRequired", sizeof(PkMediaChangeRequired), alignof(PkMediaChangeRequired));
    printf("%s;%zu;%zu\n", "PkMediaChangeRequiredClass", sizeof(PkMediaChangeRequiredClass), alignof(PkMediaChangeRequiredClass));
    printf("%s;%zu;%zu\n", "PkMediaTypeEnum", sizeof(PkMediaTypeEnum), alignof(PkMediaTypeEnum));
    printf("%s;%zu;%zu\n", "PkNetworkEnum", sizeof(PkNetworkEnum), alignof(PkNetworkEnum));
    printf("%s;%zu;%zu\n", "PkOfflineAction", sizeof(PkOfflineAction), alignof(PkOfflineAction));
    printf("%s;%zu;%zu\n", "PkOfflineError", sizeof(PkOfflineError), alignof(PkOfflineError));
    printf("%s;%zu;%zu\n", "PkPackage", sizeof(PkPackage), alignof(PkPackage));
    printf("%s;%zu;%zu\n", "PkPackageClass", sizeof(PkPackageClass), alignof(PkPackageClass));
    printf("%s;%zu;%zu\n", "PkPackageSack", sizeof(PkPackageSack), alignof(PkPackageSack));
    printf("%s;%zu;%zu\n", "PkPackageSackClass", sizeof(PkPackageSackClass), alignof(PkPackageSackClass));
    printf("%s;%zu;%zu\n", "PkPackageSackSortType", sizeof(PkPackageSackSortType), alignof(PkPackageSackSortType));
    printf("%s;%zu;%zu\n", "PkProgress", sizeof(PkProgress), alignof(PkProgress));
    printf("%s;%zu;%zu\n", "PkProgressClass", sizeof(PkProgressClass), alignof(PkProgressClass));
    printf("%s;%zu;%zu\n", "PkProgressType", sizeof(PkProgressType), alignof(PkProgressType));
    printf("%s;%zu;%zu\n", "PkRepoDetail", sizeof(PkRepoDetail), alignof(PkRepoDetail));
    printf("%s;%zu;%zu\n", "PkRepoDetailClass", sizeof(PkRepoDetailClass), alignof(PkRepoDetailClass));
    printf("%s;%zu;%zu\n", "PkRepoSignatureRequired", sizeof(PkRepoSignatureRequired), alignof(PkRepoSignatureRequired));
    printf("%s;%zu;%zu\n", "PkRepoSignatureRequiredClass", sizeof(PkRepoSignatureRequiredClass), alignof(PkRepoSignatureRequiredClass));
    printf("%s;%zu;%zu\n", "PkRequireRestart", sizeof(PkRequireRestart), alignof(PkRequireRestart));
    printf("%s;%zu;%zu\n", "PkRequireRestartClass", sizeof(PkRequireRestartClass), alignof(PkRequireRestartClass));
    printf("%s;%zu;%zu\n", "PkRestartEnum", sizeof(PkRestartEnum), alignof(PkRestartEnum));
    printf("%s;%zu;%zu\n", "PkResults", sizeof(PkResults), alignof(PkResults));
    printf("%s;%zu;%zu\n", "PkResultsClass", sizeof(PkResultsClass), alignof(PkResultsClass));
    printf("%s;%zu;%zu\n", "PkRoleEnum", sizeof(PkRoleEnum), alignof(PkRoleEnum));
    printf("%s;%zu;%zu\n", "PkSigTypeEnum", sizeof(PkSigTypeEnum), alignof(PkSigTypeEnum));
    printf("%s;%zu;%zu\n", "PkSource", sizeof(PkSource), alignof(PkSource));
    printf("%s;%zu;%zu\n", "PkSourceClass", sizeof(PkSourceClass), alignof(PkSourceClass));
    printf("%s;%zu;%zu\n", "PkStatusEnum", sizeof(PkStatusEnum), alignof(PkStatusEnum));
    printf("%s;%zu;%zu\n", "PkTask", sizeof(PkTask), alignof(PkTask));
    printf("%s;%zu;%zu\n", "PkTaskClass", sizeof(PkTaskClass), alignof(PkTaskClass));
    printf("%s;%zu;%zu\n", "PkTransactionFlagEnum", sizeof(PkTransactionFlagEnum), alignof(PkTransactionFlagEnum));
    printf("%s;%zu;%zu\n", "PkTransactionList", sizeof(PkTransactionList), alignof(PkTransactionList));
    printf("%s;%zu;%zu\n", "PkTransactionListClass", sizeof(PkTransactionListClass), alignof(PkTransactionListClass));
    printf("%s;%zu;%zu\n", "PkTransactionPast", sizeof(PkTransactionPast), alignof(PkTransactionPast));
    printf("%s;%zu;%zu\n", "PkTransactionPastClass", sizeof(PkTransactionPastClass), alignof(PkTransactionPastClass));
    printf("%s;%zu;%zu\n", "PkUpdateDetail", sizeof(PkUpdateDetail), alignof(PkUpdateDetail));
    printf("%s;%zu;%zu\n", "PkUpdateDetailClass", sizeof(PkUpdateDetailClass), alignof(PkUpdateDetailClass));
    printf("%s;%zu;%zu\n", "PkUpdateStateEnum", sizeof(PkUpdateStateEnum), alignof(PkUpdateStateEnum));
    printf("%s;%zu;%zu\n", "PkUpgradeKindEnum", sizeof(PkUpgradeKindEnum), alignof(PkUpgradeKindEnum));
    return 0;
}
